### ISSUE TITLE
Weather Warning Issue

### ISSUE THREAD

**Issue by jeepdrvr71** [riffnshred/nhl-led-scoreboard#118]
The time is over the weather warning screen. Is there a way to turn the time off on this screen.

![5251100B-FC73-496C-B398-73D303AE2BB4](https://user-images.githubusercontent.com/60526551/87874127-747ed280-c995-11ea-84b7-f741eefcbfee.jpeg)

**Comment by riffnshred** [comment]
I'll add that for future bug fix but for now go under config/layout/layout.json, scroll down to wx_alert and change the font of "advisory_ca" (for canada) or "advisory_us" (for US) from "wx_alert" to "wx_medium". If you choose set "scroll_alert" to true under weather in the config.json, the font will be at medium instead of the bigger size you currently see.

**Comment by falkyre** [comment]
This will be fixed in the next weather release.  Hopefully next week sometime now that I'm back from vacation

**Comment by riffnshred** [comment]
I believe this is fixed and can be closed @falkyre ?

**Comment by falkyre** [comment]
Yup. It's fixed. You can close it off
