### ISSUE TITLE
New Board Idea: Social Media Counter

### ISSUE THREAD

**Issue by CaptBeard** [riffnshred/nhl-led-scoreboard#206]
I think it would be great to add a board that can show you your (or any public) social media stats.

Something like:
Instagram 1,234 followers
Twitter 4,567 followers

and have it pull the info live from the internets.

**Comment by riffnshred** [comment]
Hey bud, thanks for the suggestion. I considered adding none hockey related boards in the pass and my experience is it add a lot of complexities the more I add them. Because of how we keep everything customizable to the user as much as possible, plus add the maintenance and documentation, it becomes to much work to handle. Some of the boards that are not related to hockey will be removed at some point and only the weather stuff and the clock will stay. 

Of course, nothing stops someone to fork the repo and make their own boards. I made the software as customizable as possible for that end.
