### ISSUE TITLE
Away Logo on Scoreticker Cut Off

### ISSUE THREAD

**Issue by bigbadbrad1** [riffnshred/nhl-led-scoreboard#208]
Hi I'm running the scoreboard with two 32 x 32 for effectively a 128 x 64 setup.

Everything seems to be working great, but the away logo (one on left) of score ticker always seems to get cut off in the upper right corner. The home logo seems to display nicely and doesn't overlap with the clock but is fully displayed. I haven't touched the layout from the default settings and it seems to be picking up the right layout when I start it.

I know the pixels in aren't dead because other boards work in that area.

Here's what pops up when I run:
INFO: Validating config.json.....
INFO: config.json passes validation
No data for 20202021 Playoff
No default round for 20202021 Playoff.
2021-02-19 16:13:46 INFO NHL-LED-SCOREBOARD - v1.5.7 (128x64)

Any ideas?

![image](https://user-images.githubusercontent.com/77465194/108562046-41a31100-72cd-11eb-8eec-c44c0874925c.png)

**Comment by riffnshred** [comment]
I'm not supporting any other resolution than 64x32 at the moment, I will in a relative near future. that issue is fixed in the Beta branch if you want to use that, but everything else is still not properly layout. Next update is coming March 2nd and the subsequent update will be all about expending support for other resolution.
