### ISSUE TITLE
Add Systemd instructions to the Wiki

### ISSUE THREAD

**Issue by txrangersxx** [riffnshred/nhl-led-scoreboard#356]
Any one considered adding systemd instructions to the Wiki.  I just did it myself and don't need supervisor nor screen.
It starts on bootup and stays up

**Comment by riffnshred** [comment]
Systemd was actually the original way (pre V1) of running it. But we took it out of the instruction and kept the options that was simpler for most people to use and took out the other ones and keep the wiki shorter. ofcourse, there are many ways to run this, we only cover and give support for supervisord instead of covering them all.
